name: Foo

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Print1
      run: echo "╔══[ERR"
    - name: Print2
      run: echo "╔══[LEXICAL ERROR"
    - name: Print3
      run: echo "╔══[PARSE ERROR"
    - name: Print4
      run: echo "╔══[EXPECTED ERROR"
